//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrVala.VatPayerReliabilityChecker.ServiceLibrary.Connected_Services.VatPayerReliabilityServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", ConfigurationName="VatPayerReliabilityServiceReference.rozhraniCRPDPH")]
    public interface rozhraniCRPDPH
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://adis.mfcr.cz/rozhraniCRPDPH/getStatusNespolehlivyPlatce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VatPayerReliabilityServiceReference.getStatusNespolehlivyPlatceResponse> getStatusNespolehlivyPlatceAsync(VatPayerReliabilityServiceReference.getStatusNespolehlivyPlatceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://adis.mfcr.cz/rozhraniCRPDPH/getSeznamNespolehlivyPlatce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VatPayerReliabilityServiceReference.getSeznamNespolehlivyPlatceResponse> getSeznamNespolehlivyPlatceAsync(VatPayerReliabilityServiceReference.getSeznamNespolehlivyPlatceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://adis.mfcr.cz/rozhraniCRPDPH/getStatusNespolehlivyPlatceRozsireny", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VatPayerReliabilityServiceReference.getStatusNespolehlivyPlatceRozsirenyResponse> getStatusNespolehlivyPlatceRozsirenyAsync(VatPayerReliabilityServiceReference.getStatusNespolehlivyPlatceRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public partial class StatusType
    {
        
        private System.DateTime odpovedGenerovanaField;
        
        private int statusCodeField;
        
        private string statusTextField;
        
        private BezVypisuUctuType bezVypisuUctuField;
        
        private bool bezVypisuUctuFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime odpovedGenerovana
        {
            get
            {
                return this.odpovedGenerovanaField;
            }
            set
            {
                this.odpovedGenerovanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string statusText
        {
            get
            {
                return this.statusTextField;
            }
            set
            {
                this.statusTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BezVypisuUctuType bezVypisuUctu
        {
            get
            {
                return this.bezVypisuUctuField;
            }
            set
            {
                this.bezVypisuUctuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bezVypisuUctuSpecified
        {
            get
            {
                return this.bezVypisuUctuFieldSpecified;
            }
            set
            {
                this.bezVypisuUctuFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public enum BezVypisuUctuType
    {
        
        /// <remarks/>
        ANO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public partial class Adresa
    {
        
        private string uliceCisloField;
        
        private string castObceField;
        
        private string mestoField;
        
        private string pscField;
        
        private string statField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uliceCislo
        {
            get
            {
                return this.uliceCisloField;
            }
            set
            {
                this.uliceCisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string castObce
        {
            get
            {
                return this.castObceField;
            }
            set
            {
                this.castObceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mesto
        {
            get
            {
                return this.mestoField;
            }
            set
            {
                this.mestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string psc
        {
            get
            {
                return this.pscField;
            }
            set
            {
                this.pscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string stat
        {
            get
            {
                return this.statField;
            }
            set
            {
                this.statField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public partial class NestandardniUcetType
    {
        
        private string cisloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cislo
        {
            get
            {
                return this.cisloField;
            }
            set
            {
                this.cisloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public partial class StandardniUcetType
    {
        
        private string predcisliField;
        
        private string cisloField;
        
        private string kodBankyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string predcisli
        {
            get
            {
                return this.predcisliField;
            }
            set
            {
                this.predcisliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cislo
        {
            get
            {
                return this.cisloField;
            }
            set
            {
                this.cisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kodBanky
        {
            get
            {
                return this.kodBankyField;
            }
            set
            {
                this.kodBankyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public partial class ZverejnenyUcetType
    {
        
        private object itemField;
        
        private System.DateTime datumZverejneniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nestandardniUcet", typeof(NestandardniUcetType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("standardniUcet", typeof(StandardniUcetType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime datumZverejneni
        {
            get
            {
                return this.datumZverejneniField;
            }
            set
            {
                this.datumZverejneniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformaceOPlatciRozsireneType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public partial class InformaceOPlatciType
    {
        
        private ZverejnenyUcetType[] zverejneneUctyField;
        
        private string dicField;
        
        private NespolehlivyPlatceType nespolehlivyPlatceField;
        
        private System.DateTime datumZverejneniNespolehlivostiField;
        
        private bool datumZverejneniNespolehlivostiFieldSpecified;
        
        private string cisloFuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ucet", IsNullable=false)]
        public ZverejnenyUcetType[] zverejneneUcty
        {
            get
            {
                return this.zverejneneUctyField;
            }
            set
            {
                this.zverejneneUctyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic
        {
            get
            {
                return this.dicField;
            }
            set
            {
                this.dicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NespolehlivyPlatceType nespolehlivyPlatce
        {
            get
            {
                return this.nespolehlivyPlatceField;
            }
            set
            {
                this.nespolehlivyPlatceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime datumZverejneniNespolehlivosti
        {
            get
            {
                return this.datumZverejneniNespolehlivostiField;
            }
            set
            {
                this.datumZverejneniNespolehlivostiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumZverejneniNespolehlivostiSpecified
        {
            get
            {
                return this.datumZverejneniNespolehlivostiFieldSpecified;
            }
            set
            {
                this.datumZverejneniNespolehlivostiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cisloFu
        {
            get
            {
                return this.cisloFuField;
            }
            set
            {
                this.cisloFuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public enum NespolehlivyPlatceType
    {
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        ANO,
        
        /// <remarks/>
        NENALEZEN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/")]
    public partial class InformaceOPlatciRozsireneType : InformaceOPlatciType
    {
        
        private string nazevSubjektuField;
        
        private Adresa adresaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nazevSubjektu
        {
            get
            {
                return this.nazevSubjektuField;
            }
            set
            {
                this.nazevSubjektuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Adresa adresa
        {
            get
            {
                return this.adresaField;
            }
            set
            {
                this.adresaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusNespolehlivyPlatceRequest", WrapperNamespace="http://adis.mfcr.cz/rozhraniCRPDPH/", IsWrapped=true)]
    public partial class getStatusNespolehlivyPlatceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dic")]
        public string[] dic;
        
        public getStatusNespolehlivyPlatceRequest()
        {
        }
        
        public getStatusNespolehlivyPlatceRequest(string[] dic)
        {
            this.dic = dic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusNespolehlivyPlatceResponse", WrapperNamespace="http://adis.mfcr.cz/rozhraniCRPDPH/", IsWrapped=true)]
    public partial class getStatusNespolehlivyPlatceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", Order=0)]
        public VatPayerReliabilityServiceReference.StatusType status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("statusPlatceDPH")]
        public VatPayerReliabilityServiceReference.InformaceOPlatciType[] statusPlatceDPH;
        
        public getStatusNespolehlivyPlatceResponse()
        {
        }
        
        public getStatusNespolehlivyPlatceResponse(VatPayerReliabilityServiceReference.StatusType status, VatPayerReliabilityServiceReference.InformaceOPlatciType[] statusPlatceDPH)
        {
            this.status = status;
            this.statusPlatceDPH = statusPlatceDPH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeznamNespolehlivyPlatceRequest", WrapperNamespace="http://adis.mfcr.cz/rozhraniCRPDPH/", IsWrapped=true)]
    public partial class getSeznamNespolehlivyPlatceRequest
    {
        
        public getSeznamNespolehlivyPlatceRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeznamNespolehlivyPlatceResponse", WrapperNamespace="http://adis.mfcr.cz/rozhraniCRPDPH/", IsWrapped=true)]
    public partial class getSeznamNespolehlivyPlatceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", Order=0)]
        public VatPayerReliabilityServiceReference.StatusType status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("statusPlatceDPH")]
        public VatPayerReliabilityServiceReference.InformaceOPlatciType[] statusPlatceDPH;
        
        public getSeznamNespolehlivyPlatceResponse()
        {
        }
        
        public getSeznamNespolehlivyPlatceResponse(VatPayerReliabilityServiceReference.StatusType status, VatPayerReliabilityServiceReference.InformaceOPlatciType[] statusPlatceDPH)
        {
            this.status = status;
            this.statusPlatceDPH = statusPlatceDPH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusNespolehlivyPlatceRozsirenyRequest", WrapperNamespace="http://adis.mfcr.cz/rozhraniCRPDPH/", IsWrapped=true)]
    public partial class getStatusNespolehlivyPlatceRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dic")]
        public string[] dic;
        
        public getStatusNespolehlivyPlatceRequest1()
        {
        }
        
        public getStatusNespolehlivyPlatceRequest1(string[] dic)
        {
            this.dic = dic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusNespolehlivyPlatceRozsirenyResponse", WrapperNamespace="http://adis.mfcr.cz/rozhraniCRPDPH/", IsWrapped=true)]
    public partial class getStatusNespolehlivyPlatceRozsirenyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", Order=0)]
        public VatPayerReliabilityServiceReference.StatusType status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adis.mfcr.cz/rozhraniCRPDPH/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("statusPlatceDPH")]
        public VatPayerReliabilityServiceReference.InformaceOPlatciRozsireneType[] statusPlatceDPH;
        
        public getStatusNespolehlivyPlatceRozsirenyResponse()
        {
        }
        
        public getStatusNespolehlivyPlatceRozsirenyResponse(VatPayerReliabilityServiceReference.StatusType status, VatPayerReliabilityServiceReference.InformaceOPlatciRozsireneType[] statusPlatceDPH)
        {
            this.status = status;
            this.statusPlatceDPH = statusPlatceDPH;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface rozhraniCRPDPHChannel : VatPayerReliabilityServiceReference.rozhraniCRPDPH, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class rozhraniCRPDPHClient : System.ServiceModel.ClientBase<VatPayerReliabilityServiceReference.rozhraniCRPDPH>, VatPayerReliabilityServiceReference.rozhraniCRPDPH
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public rozhraniCRPDPHClient() : 
                base(rozhraniCRPDPHClient.GetDefaultBinding(), rozhraniCRPDPHClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.rozhraniCRPDPHSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rozhraniCRPDPHClient(EndpointConfiguration endpointConfiguration) : 
                base(rozhraniCRPDPHClient.GetBindingForEndpoint(endpointConfiguration), rozhraniCRPDPHClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rozhraniCRPDPHClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(rozhraniCRPDPHClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rozhraniCRPDPHClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(rozhraniCRPDPHClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rozhraniCRPDPHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VatPayerReliabilityServiceReference.getStatusNespolehlivyPlatceResponse> getStatusNespolehlivyPlatceAsync(VatPayerReliabilityServiceReference.getStatusNespolehlivyPlatceRequest request)
        {
            return base.Channel.getStatusNespolehlivyPlatceAsync(request);
        }
        
        public System.Threading.Tasks.Task<VatPayerReliabilityServiceReference.getSeznamNespolehlivyPlatceResponse> getSeznamNespolehlivyPlatceAsync(VatPayerReliabilityServiceReference.getSeznamNespolehlivyPlatceRequest request)
        {
            return base.Channel.getSeznamNespolehlivyPlatceAsync(request);
        }
        
        public System.Threading.Tasks.Task<VatPayerReliabilityServiceReference.getStatusNespolehlivyPlatceRozsirenyResponse> getStatusNespolehlivyPlatceRozsirenyAsync(VatPayerReliabilityServiceReference.getStatusNespolehlivyPlatceRequest1 request)
        {
            return base.Channel.getStatusNespolehlivyPlatceRozsirenyAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.rozhraniCRPDPHSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.rozhraniCRPDPHSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://adisrws.mfcr.cz/adistc/axis2/services/rozhraniCRPDPH.rozhraniCRPDPHSOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return rozhraniCRPDPHClient.GetBindingForEndpoint(EndpointConfiguration.rozhraniCRPDPHSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return rozhraniCRPDPHClient.GetEndpointAddress(EndpointConfiguration.rozhraniCRPDPHSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            rozhraniCRPDPHSOAP,
        }
    }
}
